### ISSUE TITLE
Excluding audio devices, save settings, causes crash

### ISSUE THREAD

**Issue by jammysod13** [xenolightning/AudioSwitcher_v1#1494]
I exclude some audio devices from the device list, save, try switching, they're still appearing when I do quick switch (NextPlaybackDevice shortcut), I go to save again, then the app crashes.
Log file:

System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   at AudioSwitch.Forms.FormSwitcher.<SetTrayIcons>b__14(CDevice x)
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at AudioSwitch.Forms.FormSwitcher.SetTrayIcons()
   at AudioSwitch.Forms.FormSwitcher..ctor()
   at AudioSwitch.Classes.Program.Main(String[] args)
-------------------------------

**Comment by xenolightning** [comment]
That error is not from my application, try finding the correct application and logging it there.

**Comment by jammysod13** [comment]
Oh, apologies, just noticed it was AudioSwitch, not AudioSwitcher :)
That project has been archived :p

**Comment by xenolightning** [comment]
You could always use Audio Switcher instead. 

it doesn't crash when saving settings ;-)
