### ISSUE TITLE
Com Issue in peak value timer - Api issue

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#1556]
### Details:
Audio Switcher
Version: 1.6.7.96
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 64-bit
Administrator Privileges: False

### Stacktrace:
```
System.AggregateException: One or more errors occurred. ---> System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at AudioSwitcher.AudioApi.CoreAudio.Interfaces.IAudioMeterInformation.GetPeakValue(Single& peak)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at AudioSwitcher.AudioApi.CoreAudio.Threading.ComThread.Invoke(Action action)
   at AudioSwitcher.AudioApi.CoreAudio.CoreAudioSession.<.ctor>b__49_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
---> (Inner Exception #0) System.Runtime.InteropServices.InvalidComObjectException: COM object that has been separated from its underlying RCW cannot be used.
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at AudioSwitcher.AudioApi.CoreAudio.Interfaces.IAudioMeterInformation.GetPeakValue(Single& peak)
   at System.Threading.Tasks.Task.Execute()<---

```

**Comment by xenolightning** [comment]
Still an issue

**Comment by xenolightning** [comment]
Resurfaced: #1587
