### ISSUE TITLE
Custom Icon issue

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#1570]
### Details:
Audio Switcher
Version: 1.6.7.96
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False

### User Comments:
Had this error a few times now and noticed it only happens when the :Show Default Playback icon in tray" is selected.  It seems the icon is missing for my speakers not only in playback tab, but also in tray when I switch by clicking the icon in tray to switch to speakers....and then it throws this error...
### Stacktrace:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshTrayIcon()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshNotifyIconItems()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshPlaybackDevices()
```

**Comment by xenolightning** [comment]
Custom icons not showing in the application, then causing an error in the app.

**Comment by xenolightning** [comment]
#1557
