### ISSUE TITLE
Device Interface not available when device is off?

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#355]
### Details:
Audio Switcher
Version: 1.6.2.1
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False

### User Comments:
turned off av receiver
### Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudioSwitcher.AudioApi.CoreAudio.MMDevice.<get_DeviceInterfaceFriendlyName>b__8()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by xenolightning** [comment]
https://github.com/xenolightning/AudioSwitcher/issues/4
