### ISSUE TITLE
VT_EMPTY Property Keys

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#406]
### Details:
Audio Switcher
Version: 1.6.2.1
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False

### User Comments:
installing new video drivers for nvidia
### Stacktrace:
```
System.NotSupportedException: PropVariant VT_EMPTY
   at AudioSwitcher.AudioApi.CoreAudio.PropVariant.get_Value()
   at AudioSwitcher.AudioApi.CoreAudio.MMDevice.<get_DeviceInterfaceFriendlyName>b__8()
   at AudioSwitcher.AudioApi.CoreAudio.MMDevice.<get_DeviceName>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by xenolightning** [comment]
Looks to be an unexpected VT_Empty when the devices are being created, and haven't quite finished setting the properties.

**Comment by xenolightning** [comment]
Should be fixed in the latest Api version.
