### ISSUE TITLE
Custom Icon Issue Crash

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#465]
### Details:
Audio Switcher
Version: 1.6.3.1
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 64-bit
Administrator Privileges: True

### User Comments:
icon for device is missing and trying to switch causes issue

### Stacktrace:
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshTrayIcon()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshNotifyIconItems()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshPlaybackDevices()
```

**Comment by xenolightning** [comment]
Confirmed issue when the device icon is "Unknown".

An unknown entry should be added to the icon map.
