### ISSUE TITLE
Invalid Device State - Property Crash

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#521]
### Details:
Audio Switcher
Version: 1.6.3.1
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 64-bit
Administrator Privileges: True

### User Comments:
Installing graphic drivers
### Stacktrace:
```
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at AudioSwitcher.AudioApi.CoreAudio.PropertyStore.<get_Count>b__0()
   at AudioSwitcher.AudioApi.CoreAudio.PropertyStore.<>c__DisplayClass8.<Contains>b__7()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by xenolightning** [comment]
This is an issue with devices being updated and are in an invalid state.

I'll look at adding a new device state of invalid, and use that for the devices that aren't quite ready for queries.
