### ISSUE TITLE
General GDI Issues

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#814]
### Details:
Audio Switcher
Version: 1.6.4.2
Operating System: Microsoft Windows NT 6.1.7601 Service Pack 1 64-bit
Administrator Privileges: True

### Stacktrace:
```
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
   at System.Drawing.Bitmap.GetHicon()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshTrayIcon()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshNotifyIconItems()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshPlaybackDevices()
```

**Comment by xenolightning** [comment]
#815

**Comment by xenolightning** [comment]
#819 #823

**Comment by xenolightning** [comment]
#826 #827

**Comment by xenolightning** [comment]
#876

**Comment by xenolightning** [comment]
Seems to only happen when the show default icon in tray is selected.
