### ISSUE TITLE
Default Device Race Condition

### ISSUE THREAD

**Issue by xenolightning** [xenolightning/AudioSwitcher_v1#930]
### Details:
Audio Switcher
Version: 1.6.5.0
Operating System: Microsoft Windows NT 6.2.9200.0 64-bit
Administrator Privileges: False

### User Comments:
Restarting computer.  Probably from the length of time it takes the Logitech g930 to connect to the computer (it takes over a minute).
### Stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudioSwitcher.AudioApi.CoreAudio.CoreAudioDevice.get_IsDefaultDevice()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshNotifyIconItems()
   at FortyOne.AudioSwitcher.AudioSwitcher.RefreshPlaybackDevices()
```

**Comment by xenolightning** [comment]
This looks to be a race condition in GetDefaultDevice.
